"""HahaCat MiniMax H3 controlled action-reference nodes for ComfyUI."""

from .commercial import NODE_CLASS_MAPPINGS as COMMERCIAL_NODE_CLASS_MAPPINGS
from .commercial import NODE_DISPLAY_NAME_MAPPINGS as COMMERCIAL_NODE_DISPLAY_NAME_MAPPINGS
from .reserved_vram import NODE_CLASS_MAPPINGS as RESERVED_VRAM_NODE_CLASS_MAPPINGS
from .reserved_vram import NODE_DISPLAY_NAME_MAPPINGS as RESERVED_VRAM_NODE_DISPLAY_NAME_MAPPINGS
from .action_reference import NODE_CLASS_MAPPINGS as ACTION_NODE_CLASS_MAPPINGS
from .action_reference import NODE_DISPLAY_NAME_MAPPINGS as ACTION_NODE_DISPLAY_NAME_MAPPINGS
from .storyboard import NODE_CLASS_MAPPINGS as STORYBOARD_NODE_CLASS_MAPPINGS
from .storyboard import NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for mappings in (
    COMMERCIAL_NODE_CLASS_MAPPINGS,
    RESERVED_VRAM_NODE_CLASS_MAPPINGS,
    ACTION_NODE_CLASS_MAPPINGS,
    STORYBOARD_NODE_CLASS_MAPPINGS,
):
    NODE_CLASS_MAPPINGS.update(mappings)

for mappings in (
    COMMERCIAL_NODE_DISPLAY_NAME_MAPPINGS,
    RESERVED_VRAM_NODE_DISPLAY_NAME_MAPPINGS,
    ACTION_NODE_DISPLAY_NAME_MAPPINGS,
    STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS,
):
    NODE_DISPLAY_NAME_MAPPINGS.update(mappings)

WEB_DIRECTORY = "./storyboard/web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
